# Generated by Django 4.2.5 on 2023-09-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_stock_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=225)),
                ('password_hash', models.CharField(max_length=225)),
                ('last_login_date', models.DateTimeField(null=True)),
                ('registration_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
