# Generated by Django 4.2.5 on 2023-09-28 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAccount',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=225)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
            options={
                'db_table': 'StockAccount',
            },
        ),
    ]
