# Generated by Django 4.2.5 on 2023-09-28 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_stockaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holdings',
            fields=[
                ('holding_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(null=True)),
                ('total_invested_amount', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.stockaccount')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.stock')),
            ],
            options={
                'db_table': 'Holdings',
            },
        ),
    ]
