# Generated by Django 4.2.5 on 2023-09-28 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_holdings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPortfolioStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('total_investment', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_market_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_profit_loss', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
            options={
                'db_table': 'MonthlyPortfolioStatus',
            },
        ),
    ]
