# Generated by Django 4.2.5 on 2023-09-28 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_monthlyportfoliostatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_date', models.DateTimeField()),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_transaction_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.stockaccount')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.stock')),
            ],
            options={
                'db_table': 'StockTransaction',
            },
        ),
        migrations.CreateModel(
            name='MonthlyPortfolioStockStatus',
            fields=[
                ('stock_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invested_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.stockaccount')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
            options={
                'db_table': 'MonthlyPortfolioStockStatus',
            },
        ),
    ]
